### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by AdamWill** [release-engineering/productmd#102]
Could you please cut a release of productmd and send it out to Fedora and RHEL/EPEL at some point? I'd like to use the 'unique image identifier' stuff I wrote and you merged (thanks!) in [fedfind](https://pagure.io/fedora-qa/fedfind) to replace its own image identification approach, but can't until it's in an official release and the packages are updated. Thanks!

**Comment by lubomir** [comment]
I just made a new release today, so the package soon to land in updates testing should exactly match what's in current `master` branch.

However I'm not sure which feature you're missing. I think the unique image identification should be available for quite some time already (since 1.5).

**Comment by AdamWill** [comment]
aha! I was looking at the 'releases' tab on github; somehow I missed that there were several newer releases which hadn't been done as github releases, only tagged. So that's fine, I'll close this. Thanks.
