### ISSUE TITLE
get_release_id(major_version=True) doesn't work well with layered products using X.Y.Z version scheme

### ISSUE THREAD

**Issue by lkocman** [release-engineering/productmd#121]
Hello

I'm using  compose.info.get_release_id(major_version=True) on a product/release which is three digit version scheme e.g 99.0.0  for this example. And compose.info.get_release_id(major_version=True) is not behaving correctly.

I see that def get_major_version(version, remove=1) is parametrized and seems like we're simply always using default remove value.

```
>>> compose = productmd.compose.Compose("/home/lkocman/Product-99.0.0-BASEPRODUCT-99")
>>> compose.info
<productmd.composeinfo.ComposeInfo object at 0x931e90>

>>> compose.info.get_release_id()
u'Product-99.0.0-BASEPRODUCT-99'

# I would expect Product-99-BASEPRODUCT-99 as 99 is the major version
>>> compose.info.get_release_id(major_version=True)
u'Product-99.0-BASEPRODUCT-99'

```

**Comment by lubomir** [comment]
The major version is determined by removing a given number of parts from the version. I'm not sure what's the reason why it does not simply always take the first part as major version.

We could change `get_release_id` to be able to specify how many parts to remove, and the caller would have to know what number to pass in. Would that work for your use case?

**Comment by lkocman** [comment]
I'd be probably more up for a call which gives you id just with major versions, otherwise it's easier for me to slice it myself.
