### ISSUE TITLE
Parse of opensuse treeinfo fails.

### ISSUE THREAD

**Issue by pavelpicka** [release-engineering/productmd#141]
When parsing opensuse treeinfo[0] productmd raise the expcetion[1]
`Platform has images but is not referenced in platform list: x86_64, set()`
In my opinion they(suse) use it pretty simplified but will really helpful to be able to parse their treeinfo too.

[0] http://download.opensuse.org/distribution/leap/15.1/repo/oss/.treeinfo
[1] https://github.com/release-engineering/productmd/blob/681ba919f079688adc5832ab0538bdfb123d2534/productmd/treeinfo.py#L833

**Comment by lubomir** [comment]
Can you share more details about how you're parsing the file? I'm getting more errors before it gets to the validation.

**Comment by fabricio-aguiar** [comment]
@lubomir the problem is described here: https://github.com/pulp/pulp_rpm/pull/1639
Basically we were doing deserialization with the wrong order, but when we fixed it, productMD required the `short` field, which this OpenSUSE repo doesn't have, and this repo also doesn't have a `timestamp`

**Comment by lubomir** [comment]
Please try the linked PR. I'll need to think about it a bit more to make sure it's not breaking something.

**Comment by fabricio-aguiar** [comment]
@lubomir it worked!
Thanks!

**Comment by lubomir** [comment]
The patched is merged and included in release 1.25. It should already be available on PyPI.

**Comment by pavelpicka** [comment]
Great news, thank you!
