### ISSUE TITLE
RPMs file format documentation is inconsistent with code

### ISSUE THREAD

**Issue by lubomir** [release-engineering/productmd#16]
In [the documentation each RPM has a field named `type`](http://release-engineering.github.io/productmd/rpms-1.0.html).

However, when you create the file using the functions in the library and serialize it, the field will be called `category`.

It is possible to parse both with no errors, but the Python representation will obviously be different and cause consuming code to fail.

**Comment by dmach** [comment]
Already fixed in commit 8e16748912b7710e886e7a2bb20c0b88652da767
