### ISSUE TITLE
pip install fails for v1.3 on Python 3

### ISSUE THREAD

**Issue by csomh** [release-engineering/productmd#60]
Description:
Running `pip install productmd` fails with the following error on Python 3:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aap2fih6/productmd/setup.py", line 25, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

How to reproduce:
1. Create and activate virtenv with Python 3
```
$ mkvirtualenv -p python3.5 pmd
```

2. Install productmd with pip
```
$ pip install productmd
```

**Comment by lubomir** [comment]
Oh, I only tested it with python2 where the prebuild wheel is used. The file is not included in the tarball.

**Comment by lubomir** [comment]
I have uploaded fixed tarball to PyPI. Installation with `pip` on Python 3.5 now works. It may try to reuse the previously downloaded tarball from a local cache. Use `--no-cache-dir` to force it download the new one.

Thank you very much for the report.

**Comment by csomh** [comment]
Thank you very much for the quick fix :+1:
