### ISSUE TITLE
productmd on pypi cannot by installed with pip

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/productmd#67]
I have `setup.py` with this snippet:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, find_packages

setup(
    install_requires=['pdc-client', 'productmd'],
```
when I install this with `python setup.py develop` I end up with error:
```Searching for productmd
Reading https://pypi.python.org/simple/productmd/
Best match: productmd 1.3
Downloading https://pypi.python.org/packages/d0/33/e4b0c10d3a1f3beaa164338774ead0f7ab6eaf662db4c4a8103f8cf6e515/productmd-1.3.tar.bz2#md5=ef826d4ca3d259294f12545fd5e17618
Processing productmd-1.3.tar.bz2
Writing /tmp/easy_install-BLQA0i/productmd-1.3/setup.cfg
Running productmd-1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BLQA0i/productmd-1.3/egg-dist-tmp-NeluU9
error: requirements.txt: No such file or directory
```

Apparently current version of productmd (1.3) on pipy references `requirements.txt` which isn't present in the upstream archive:
```
# Manage dependencies in requirements.txt
with open('requirements.txt') as f:
    reqs = f.read().splitlines()
```

Please upload current version of productmd there.

Note: with `pip install productmd` I don't see this issue and productmd is installed correctly.

**Comment by lubomir** [comment]
There are three artifacts on PyPI currently: prebuilt wheel, .tar.gz and .tar.bz2. Only the .tar.gz archive is incorrect. Related issue is #60. I don't think it's possible to fix just the tarball, so this will have to be fixed with a new release.

**Comment by lubomir** [comment]
1.4 has been released and should fix this problem.
