### ISSUE TITLE
Spec diverged in Fedora

### ISSUE THREAD

**Issue by lubomir** [release-engineering/productmd#79]
@AdamWill enabled building Python 3 subpackages in EPEL 6 and 7:
https://src.fedoraproject.org/cgit/rpms/python-productmd.git/commit/?id=492bd7e60e0565192f8b6d28459b7cb511ad53da

This means we need to update the spec file in this repo or tito would drop those changes on next release.

However the problem is that the updated spec file no longer builds internally.

**Comment by AdamWill** [comment]
ah, sorry about that, I didn't realize the spec was maintained in SCM. This kind of thing would happen a lot less often if people indicated prominently in a spec file itself when that spec file is being maintained in some sort of external SCM :/

**Comment by AdamWill** [comment]
https://github.com/release-engineering/productmd/pull/80 should fix this, I hope. Sorry for the trouble.

**Comment by lubomir** [comment]
Thank you very much, this indeed makes it work again.
